import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "react-oidc-context";

export const metadata: Metadata = {
  title: "AlignSync Pro",
  description: "Generated by create next app",
};

// Cognito OIDC config
const cognitoAuthConfig = {
  authority: "https://cognito-idp.eu-north-1.amazonaws.com/eu-north-1_Exiy18u5t", // replace with your user pool
  client_id: "3m2u0jjjd52c9oie6f2189976a", // your app client ID
  redirect_uri: "https://main.d1yv3ay871rrrx.amplifyapp.com/", // your deployed URL
  response_type: "code",
  scope: "openid email profile phone",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthProvider {...cognitoAuthConfig}>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
